apiVersion: v1
kind: Service
metadata:
  labels:
    app: ucu-de-devops-hw4-part-4
  name: ucu-de-devops-hw4-part-4
spec:
  ports:
    - name: http
      port: 8050
      targetPort: http
  selector:
    app: ucu-de-devops-hw4-part-4
  type: ClusterIP
